import argparse
import os


def predict(img_path, model, class_dict, img_size=(299, 299), show=True):
    import matplotlib.pyplot as plt
    import numpy as np
    from PIL import Image

    if not os.path.isfile(img_path):
        raise FileNotFoundError(f"Image not found: {img_path}")

    label = [name for name, _ in sorted(class_dict.items(), key=lambda item: item[1])]
    img = Image.open(img_path)
    resized_img = img.resize(img_size)
    img = np.asarray(resized_img)
    img = np.expand_dims(img, axis=0)
    img = img / 255
    predictions = model.predict(img)
    probs = list(predictions[0])
    labels = label

    if show:
        plt.figure(figsize=(12, 12))
        plt.subplot(2, 1, 1)
        plt.imshow(resized_img)
        plt.subplot(2, 1, 2)
        bars = plt.barh(labels, probs)
        plt.xlabel("Probability", fontsize=15)
        ax = plt.gca()
        ax.bar_label(bars, fmt="%.2f")
        plt.show()

    return dict(zip(labels, probs))


def parse_args():
    parser = argparse.ArgumentParser(description="Predict one brain tumor MRI image.")
    parser.add_argument("--image", required=True, help="Path to image.")
    parser.add_argument(
        "--model",
        default="artifacts/brain_tumor_xception.keras",
        help="Path to trained Keras model.",
    )
    parser.add_argument(
        "--class-indices",
        default="artifacts/class_indices.json",
        help="Path to class_indices.json generated by train.py.",
    )
    parser.add_argument("--img-size", type=int, nargs=2, default=(299, 299))
    parser.add_argument("--no-show", action="store_true", help="Disable plot window.")
    return parser.parse_args()


def main():
    args = parse_args()
    from tensorflow.keras.models import load_model

    from utils import load_class_indices

    if not os.path.isfile(args.model):
        raise FileNotFoundError(
            f"Model file not found: {args.model}. Run train.py first or pass --model."
        )

    model = load_model(args.model)
    class_dict = load_class_indices(args.class_indices)
    result = predict(
        args.image,
        model,
        class_dict,
        img_size=tuple(args.img_size),
        show=not args.no_show,
    )

    for label, prob in result.items():
        print(f"{label}: {prob:.4f}")


if __name__ == "__main__":
    main()
